### ISSUE TITLE
Paper for reference

### ISSUE THREAD

**Issue by cy1c0n9** [josdavidmo/encrypt_video#1]
Hi there,

Nice script! I am wondering if there are any paper related to this implementation so that we can reference from? It looks like implementation for some academic articles.

Thank you very much in advance.

**Comment by josdavidmo** [comment]
Hi! Yeah there is, if you provide me an email I can send you a copy. josdavidmo@gmail.com. English and Spanish! 😁

**Comment by cy1c0n9** [comment]
Thank you very much for that! This is my email: cy1c0n9@gmail.com
Cheers mate!
